# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newPRWelcomeComment: |
  💖 Thanks for opening this pull request! 💖

  We use semantic commit messages to streamline the release process. Before your pull request can be merged, you should **update your pull request title** to start with a semantic prefix. 
  
  For example, if your pull request is to fix a bug, you should update your title to start with `fix:`. If your pull request is to add a new feature, you should update your title to start with `feat:`. etc.

  Things that will help get your PR across the finish line:

    - [ ] Update your pull request title to start with a semantic prefix    
    - [ ] Add a description of your changes
    - [ ] Add a README.md if you are adding a new project
    - [ ] Add a link to your project in the README.md of this project
    - [ ] Include screenshots and animated GIFs whenever possible in your project's README.md

All pull requests on this repo, will eventually be merged so please be patient and we will get back to you as soon as we can.



# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! Be proud of you! 🎉🎉🎉

# It is recommend to include as many gifs and emojis as possible
